FBuildings = ['Farms']
HBuildings = ['No Walls', 'Well', 'Longhouse', '2-3 Work houses', '>15 Hovels']
VBuildings = ['Wooden Walls', '3 Wells', 'Manor House', 'Great Hall', 'Church', 'Blacksmith', 'Inn', '4-5 Work houses', '2-3 Shopfronts', '>30 Hovels', '>15 Homesteads']
TBuildings = ['Stone Walls', 'Great Hall', '1-2 Church', '2-3 Blacksmiths', '2-3 Inns', '10 Work houses', '7-10 Shopfronts', 'Dedicated Market', '>100 Hovels', '>40 Homesteads']
CBuildings = ['Towers', 'Sewers', '2-4 Government Buildings', '4+ Blacksmiths', '5+ Inns', '10+ Processing', '20+ Shopfronts', 'Dedicated Market', '3-4 Watch Barracks', '>200 Hovels', '>100 Homesteads', '>50 Manors']
