import random

Settlement_Features = [
    "Arms (weapons, armor or gunsmiths)",
    "Books",
    "Brewing",
    "Center of learning",
    "Crumbling ramparts or palisade",
    "Eerie ruin on the edge of the settlement",
    "Famous for a yearly feast or festival",
    "Famous/notorious coaching inn(s)",
    "Foodstuffs",
    "Glass or pottery crafters",
    "Goats (meat, cheese and furs)",
    "Government (provincial court, office etc)"
    "Home of famous artist, actor or author",
    "Horse breeding",
    "Illicit services (strong thieves guild etc)",
    "Important agricultural producer",
    "Imposing bridge or other construction",
    "Impressive shrine, statue or memorial",
    "Impressive temple to major diety",
    "Inhabitants are ostracized by outsiders",
    "Known as a lawless place",
    "Large Dwarven community ({}%)".format(random.randint(1,10)*2),
    "Large library",
    "Large producer of charcoal",
    "Location makes settlement a natural fort",
    "Logging, timber and sawing",
    "Lush park, gardens or commons",
    "Major Road/River Warden station",
    "Mentioned in famous song, saga or poem",
    "Mighty watch tower or beacon",
    "Military strongpoint (double garrison)",
    "Mining (metal or mineral)",
    "Notorious for its corrupt officials",
    "On the decline (economically, politically)",
    "Part of the settlement is in ruins",
    "Preserves",
    "Recently under attack (by Greenskins etc)",
    "Rumoured to be a site of unnatural events",
    "Settlement has recently been prospering",
    "Settlement is geographically isolated",
    "Settlement of historical importance",
    "Sheep (meat, cheese and fur)",
    "Significant center of trade",
    "Significant fortification (25% of population are troops)",
    "Site of major prison or labour camp",
    "Site of recent unrest (riots, insurrections)",
    "Sizable Halfling community ({}%)".format(random.randint(1,10)*2),
    "Tradesmen are regarded as greedy",
    "Trapping (fur and skin)",
    "Wine (type depends on soil and tradition)"
]
